# Data Science Project

In [21]:
# Library importation
import matplotlib.pyplot as plt  # basic visualisation
import pandas as pd  # pandas
import seaborn as sns
from jinja2 import Template
import webbrowser
import os

# import pyarrow.parquet as pq
import pyarrow as pa  # as online files are stored in parquet, pyarrow is used to bypass need to import native requests and csv libraries
import numpy as np
import csv
import plotly.express as px

In [2]:
# data_frames
# NOTE:Health Screen Size extremely low
df_blood = pd.read_csv("./blood_donations.csv")
df_blood.name = "df_blood"
df_blood_state = pd.read_csv("./blood_donations_state.csv")
df_blood_state.name = "df_blood_state"
df_health_screen = pd.read_csv("./infant_immunisation.csv")
df_health_screen.name = "df_health_screen"
df_organ_pledges = pd.read_csv("./pekab40_screenings_state.csv")
df_organ_pledges.name = "df_organ_pledges"
df_covid_deaths = pd.read_csv("./covid_cases.csv")
df_covid_deaths.name = "df_covid_deaths"
df_covid_cases = pd.read_csv("./covid_deaths_linelist.csv")
df_covid_cases.name = "df_covid_cases"
df_list = [
    df_blood,
    df_blood_state,
    df_health_screen,
    df_organ_pledges,
    df_covid_cases,
    df_covid_deaths,
]

In [ ]:
file_path = 'index.html'

# Ensure the file exists and is accessible
if os.path.isfile(file_path):
    # Open the file in the default browser
    webbrowser.open(f'file://{os.path.realpath(file_path)}')
else:
    print(f"File not found: {file_path}")print(f"Blood Sample Size:{df_blood.shape}")
print(f"Blood Sample Size:{df_blood_state.shape}")
print(f"Health Screen Size:{df_health_screen.shape}")
print(f"Organ Pledges:{df_organ_pledges.shape}")
print(f"Covid Deaths:{df_covid_deaths.shape}")

print(f"Covid Cases:{df_covid_cases.shape}")

Blood Sample Size:(36890, 3)
Blood Sample Size:(479570, 4)
Health Screen Size:(120, 3)
Organ Pledges:(40416, 3)
Covid Deaths:(33218, 7)
Covid Cases:(37351, 15)

In [4]:
# Data Cleaning and Duplicate/Null Value Identification
for _ in df_list:
    null_count = _.isnull().sum().sum()
    duplicate_count = _.isnull().sum().sum()
    if null_count > 0:
        print(f"{_.name} has null values")
        print(null_count)
    elif duplicate_count > 0:
        print(f"{_.name} has duplicate values")
        print(duplicate_count)
    else:
        print(f"{_.name} is clean")

df_blood is clean
df_blood_state is clean
df_health_screen has null values
8
df_organ_pledges is clean
df_covid_cases has null values
172716
df_covid_deaths is clean

In [5]:
# Cleaning Covid Deaths
cleaned_df_covid_cases = df_covid_cases.dropna(axis=1)
df_organ_pledges

             date           state  screenings
0      2019-04-15           Johor           0
1      2019-04-16           Johor          12
2      2019-04-17           Johor          18
3      2019-04-18           Johor          17
4      2019-04-19           Johor           5
...           ...             ...         ...
40411  2026-03-10  W.P. Putrajaya           2
40412  2026-03-11  W.P. Putrajaya           0
40413  2026-03-12  W.P. Putrajaya           0
40414  2026-03-13  W.P. Putrajaya           0
40415  2026-03-14  W.P. Putrajaya           0

[40416 rows x 3 columns]

In [11]:
# Basic Data Exploration of COVID, Organ Pledges and Blood Sample Sizes By Statd
df_covid_cases.head()

,date,date_announced,date_positive,date_dose1,date_dose2,date_dose3,brand1,brand2,brand3,state,age,male,bid,malaysian,comorb
0,2020-03-17,2020-03-17,2020-03-12,NaN,NaN,NaN,NaN,NaN,NaN,Johor,34,1,0,1,1
1,2020-03-17,2020-03-17,2020-03-15,NaN,NaN,NaN,NaN,NaN,NaN,Sarawak,60,1,0,1,1
2,2020-03-20,2020-03-20,2020-03-11,NaN,NaN,NaN,NaN,NaN,NaN,Sabah,58,1,0,1,1
3,2020-03-21,2020-03-21,2020-03-13,NaN,NaN,NaN,NaN,NaN,NaN,Melaka,50,1,0,1,1
4,2020-03-22,2020-03-22,2020-03-20,NaN,NaN,NaN,NaN,NaN,NaN,Sarawak,80,0,1,1,1

In [ ]:
# CLI Format

In [ ]:
# Plotly Dashboard Creation
# Do multiple boxplots comparing state by state
organ_pledges = px.box(df_organ_pledges, x="state", y="screenings")
covid_cases = px.box(df_covid_cases, x="state", y="age")
fig = covid_cases
# chloropleth state maps

In [19]:
# Basic Web App Extension of KKM Now
# Integrate boxplots into a basic web app flow
# Use AGI to create boilerplate web app templates
with open("template.html") as f:
    j2_template = Template(f.read())
with open("plotly_graph.html", "w", encoding="utf-8") as f:
    f.write(j2_template.render(fig=fig.to_html(full_html=False)))

In [ ]:
# File Opening
file_path = "plotly_graph.html"

# Ensure the file exists and is accessible
if os.path.isfile(file_path):
    # Open the file in the default browser
    webbrowser.open(f"file://{os.path.realpath(file_path)}")
else:
    print(f"File not found: {file_path}")